sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
#- '3.7'
- 'pypy'
- 'pypy3.5'
matrix:
  include:
  - env: TOXENV=py37
    python: 3.7
    sudo: required
    dist: xenial
install:
- pip install tox-travis
script: tox
