sudo: false
dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 'pypy3.5'
cache: pip
install:
- pip install codecov
- pip install tox-travis
script: tox -- --cov
after_script:
- codecov
